name: Angular CI & Firebase Deployment

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    outputs:
      build-path: ${{ steps.set-build-path.outputs.build-path }}
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Build Angular app
        id: build-app
        run: |
          if [ -f package.json ] && grep -q "\"build\"" package.json; then
            npm run build --if-present
            echo "::set-output name=build-path::dist/$(ls dist)"
          else
            ng build --prod
            echo "::set-output name=build-path::dist/$(ls dist)"
          fi

      - name: Run tests
        run: |
          if npm run test --if-present; then
            echo "Ran npm test script"
          else
            ng test --watch=false --browsers=ChromeHeadlessCI
          fi

      - name: Set build artifact
        id: set-build-path
        run: echo "build-path=$(ls dist)" >> $GITHUB_OUTPUT

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: angular-build
          path: dist/**

  preview_deploy:
    if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: angular-build
          path: dist

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_INTERVIEW_PREP_AF37B }}
          projectId: interview-prep-af37b

  live_deploy:
    if: github.event_name == '_
